### ISSUE TITLE
Redundancy 

### ISSUE THREAD

**Issue by petercroce** [syllable-hq/uphs-feasibility-study#2]
In the paragraph linked below, the sentences that begin "however" and "but" are duplicative. 

I would suggest replacing the "but" sentence with the "however" sentence (removing the "but" sentence) so the stuff about PHS not getting attention comes before the "however, sentiment shifting back to PHS" sentence. 

https://github.com/syllable-hq/uphs-feasibility-study/blob/f295126ec048fd687d7e06194fa9dde7b18e0824/underground-pumped-hydroelectric-storage-feasibility-study.tex#L283

**Comment by erchaves** [comment]
Nice catch, thanks
